import type { DashboardData, DashboardVideo, ProductionStatus } from "@/lib/types";

const statuses: ProductionStatus[] = [
  "research",
  "script",
  "video",
  "title",
  "thumbnail",
  "scheduled",
  "published",
  "analyzed",
];

export const demoVideos: DashboardVideo[] = ([
  {
    id: "demo-pivot-1",
    videoId: "7jVYmU2TSB4",
    title: "【自己流で疲弊しない】Gemini最強壁打ち術／同期と競合に勝つAIプロンプト",
    themeSummary: "Geminiビジネス壁打ち術",
    url: "https://www.youtube.com/watch?v=7jVYmU2TSB4",
    channelName: "pivot",
    publishedOn: "2026-05-13",
    durationText: "20分56秒",
    latestViews: 12046,
    sevenDayAverageGrowth: 0,
    likeCount: 189,
    commentCount: 10,
    tags: ["pivot", "AI", "プロンプト", "ビジネス虎の巻"],
    productionStatus: "research",
    hasTranscript: false,
  },
  {
    id: "demo-tbs-1",
    videoId: "J_F3IaV2-5c",
    title: "【Claude「80倍成長」でAIインフラが限界】需要予測はOpenAIが一枚上手",
    themeSummary: "AIインフラとAnthropicの成長",
    url: "https://www.youtube.com/watch?v=J_F3IaV2-5c",
    channelName: "TBS CROSS DIG",
    publishedOn: "2026-05-12",
    durationText: "56分59秒",
    latestViews: 121067,
    sevenDayAverageGrowth: 28642,
    likeCount: 1900,
    commentCount: 103,
    tags: ["AI", "Claude", "TBS", "経済ニュース"],
    productionStatus: "script",
    hasTranscript: true,
    obsidianPath: "/Users/ha_m/Desktop/Obsidian Vault/2026-05-12 Claude 80倍成長.md",
    githubPath: "transcripts/2026/05/2026-05-12__J_F3IaV2-5c__Claude.md",
  },
  {
    id: "demo-pivot-2",
    videoId: "IK82JK6HZxI",
    title: "【2800万人の超巨大市場。中年を攻略せよ！】団塊ジュニアとポスト団塊",
    themeSummary: "2800万人の中年市場攻略法",
    url: "https://www.youtube.com/watch?v=IK82JK6HZxI",
    channelName: "pivot",
    publishedOn: "2026-05-13",
    durationText: "34分38秒",
    latestViews: 19521,
    sevenDayAverageGrowth: 0,
    likeCount: 204,
    commentCount: 24,
    tags: ["中年", "市場", "PIVOT"],
    productionStatus: "thumbnail",
    hasTranscript: false,
  },
  {
    id: "demo-local-1",
    videoId: "hUCPzN2FIZQ",
    title: "間違った言語化があなたの成果を奪う！年商100億企業社長が教える”真の言語化”",
    themeSummary: "言語化と解像度で再現性を高める",
    url: "https://www.youtube.com/watch?v=hUCPzN2FIZQ",
    channelName: "北の達人チャンネル",
    publishedOn: "2025-02-18",
    durationText: "16:13",
    latestViews: 0,
    sevenDayAverageGrowth: 0,
    likeCount: 0,
    commentCount: 0,
    tags: ["言語化", "仕事術", "解像度"],
    productionStatus: "analyzed",
    hasTranscript: true,
    obsidianPath:
      "/Users/ha_m/Desktop/Obsidian Vault/2025-02-18 間違った言語化があなたの成果を奪う！年商100億企業社長が教える”真の言語化”.md",
    githubPath: "transcripts/2025/02/2025-02-18__hUCPzN2FIZQ__true-language.md",
  },
  {
    id: "demo-tbs-2",
    videoId: "PMkdy4P7GoE",
    title: "【中国内陸で“模擬台北”が拡大中】習体制で「武力統一」の現実味",
    themeSummary: "中国による台湾武力統一の現実味",
    url: "https://www.youtube.com/watch?v=PMkdy4P7GoE",
    channelName: "TBS CROSS DIG",
    publishedOn: "2026-05-12",
    durationText: "42分57秒",
    latestViews: 11554,
    sevenDayAverageGrowth: 6666,
    likeCount: 168,
    commentCount: 73,
    tags: ["ニュース", "中国", "台湾", "経済"],
    productionStatus: "video",
    hasTranscript: false,
  },
  ] as DashboardVideo[]).map((video, index): DashboardVideo => ({
  ...video,
  assignedTo: index % 2 === 0 ? "producer@example.com" : "editor@example.com",
  dueOn: index % 2 === 0 ? "2026-05-20" : null,
  productionStatus: video.productionStatus ?? statuses[index % statuses.length],
}));

export const demoDashboardData: DashboardData = {
  mode: "demo",
  setupWarnings: [
    "Supabase環境変数が未設定のため、Drive実データではなくデモデータを表示しています。",
  ],
  channels: [
    {
      id: "demo-channel-pivot",
      name: "pivot",
      driveSheetName: "pivot",
      genre: "ビジネス",
      status: "active",
      videoCount: 2,
    },
    {
      id: "demo-channel-tbs",
      name: "TBS CROSS DIG",
      driveSheetName: "TBS CROSS DIG",
      genre: "ニュース",
      status: "active",
      videoCount: 2,
    },
    {
      id: "demo-channel-kitanotatsujin",
      name: "北の達人チャンネル",
      driveSheetName: "manual",
      genre: "仕事術",
      status: "active",
      videoCount: 1,
    },
  ],
  videos: demoVideos,
  syncRuns: [
    {
      id: "demo-sync",
      type: "drive",
      status: "success",
      message: "demo sync complete",
      createdAt: new Date().toISOString(),
    },
  ],
  workerJobs: [
    {
      id: "demo-job",
      type: "transcribe",
      status: "queued",
      createdAt: new Date().toISOString(),
      payload: { url: "https://www.youtube.com/watch?v=..." },
    },
  ],
};
